const text1 =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";
const text2 =
  "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur";
const text3 =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce euismod sagittis leo, ac commodo enim volutpat sed. Vestibulum diam mi, consectetur eget tincidunt ut, vehicula id enim. Nullam lorem leo, porttitor at augue non, suscipit varius magna. Ut sagittis nibh vel turpis convallis, vitae sollicitudin mauris molestie. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse non justo sed tortor pellentesque semper in at elit. Mauris ipsum eros, vestibulum sit amet vulputate non, rutrum eu magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean cursus id enim non tincidunt. Phasellus pretium eleifend quam non rutrum. Praesent eleifend varius dolor ut sagittis. Etiam varius consectetur lacus, a ornare lacus dapibus vel. Nullam non ultrices metus, ac porta orci. Morbi tincidunt, est ut convallis finibus, velit neque consequat arcu, imperdiet scelerisque diam felis a dui. Vivamus facilisis venenatis est at venenatis.";
const text4 =
  "Maecenas lacinia lectus at dui mollis, non rhoncus leo ornare. Duis hendrerit quis mauris at lacinia. Cras sed dictum leo. Donec ultricies urna sed tristique porta. Ut luctus ultricies scelerisque. Pellentesque elementum rhoncus est. Quisque eget urna ut risus porttitor venenatis. In egestas in urna a cursus. Suspendisse dolor magna, tincidunt eu sem a, consectetur aliquam lorem. Quisque nec lobortis eros, eu auctor risus. Aenean ut nibh at eros viverra egestas in elementum leo. Nam vitae sagittis orci.";
const text5 =
  "Nam libero urna, vulputate nec velit non, imperdiet pretium sapien. Proin dapibus elit at facilisis feugiat. Sed id commodo nisi, a iaculis nunc. Nulla quis neque consectetur mauris feugiat mollis. Sed iaculis porttitor leo. Vestibulum varius nulla a eros sodales euismod. Etiam feugiat mauris sed tincidunt dignissim. Nulla sagittis, mauris at faucibus bibendum, velit metus cursus enim, sed dapibus velit quam at eros. Maecenas eu porttitor metus, et cursus orci. Vestibulum lobortis consequat arcu, et commodo eros facilisis sit amet. Vestibulum et commodo ligula. Nulla vulputate molestie urna sed hendrerit. Morbi elementum pulvinar pulvinar. Proin luctus odio eu mi molestie, quis posuere mauris mollis. Nunc id odio id urna efficitur rhoncus a non nulla. Pellentesque sollicitudin eros id mauris pharetra, sit amet venenatis libero ultrices. ";
const text6 =
  "Suspendisse in dictum nulla, vitae accumsan quam. Maecenas vitae erat eu velit congue sodales. Aenean at elit consequat, facilisis lacus sed, elementum lorem. Sed viverra purus semper enim blandit euismod. Nulla at consequat ante. Suspendisse est eros, maximus pulvinar iaculis quis, lacinia nec erat. Proin nec purus ac mauris sodales elementum. Sed eget laoreet metus. ";
const text7 =
  "Curabitur congue, est vel consectetur vulputate, arcu nunc malesuada sem, sed condimentum ipsum quam sit amet libero. Curabitur eu odio in felis rhoncus facilisis. Sed sodales varius urna, eu auctor ligula elementum eget. Vivamus sed quam sed lectus commodo mollis. Maecenas interdum arcu tincidunt tincidunt condimentum. Nulla ut vestibulum neque, id facilisis elit. Nulla sed orci at enim imperdiet feugiat a ac odio. Morbi sem neque, ultricies ac metus id, efficitur ultrices magna. Praesent in orci at tellus tempus imperdiet sed eget nulla. Phasellus a lectus sollicitudin ligula tempor finibus in et tortor. Fusce vehicula sapien et auctor fringilla. Suspendisse aliquam at ex quis commodo. ";
export { text1, text2, text3, text4, text5, text6, text7 };
